#!/usr/bin/env bash
#Lucky/unlucky numbers
x=1
while [ $x -le 20 ]
do
    case "$x" in
	4) echo -e "bad luck China"
    x=$(( x + 1 ))
        ;;
	9) echo -e "bad luck Japan"
    x=$(( x + 1 ))
        ;;
	17) echo -e "bad luck Italy"
    x=$(( x + 1 ))
        ;;  
esac	
    echo "Best School"
x=$(( x + 1 ))
done
