#!/usr/bin/env bash
#Display hours and minutes
hour=0
while [ $hour -le 12 ]
do
    echo Hour: $hour
    hour=$(( h + 1 ))
    minute=0
    while [ $minute -le 59 ]
    do
	echo $minute
	minute=$(( m + 1 ))
	if [ $minute -eq 59 ]
	then
	    $hour=$(( n + 1 ))
	    fi
	break
    done
    
